#### Get all users
GET http://localhost:3000/user
Content-Type: application/json

#### Get user
GET http://localhost:3000/user/1
Content-Type: application/json

### Create user
POST http://localhost:3000/user
Content-Type: application/json

{
	"id": 1,
	"fullName": "John Doe"
}

### Update user
PUT http://localhost:3000/user/1
Content-Type: application/json

{
	"fullName": "Jane Doe"
}

#### Delete user
DELETE http://localhost:3000/user/1
Content-Type: application/json
